theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
twitter:
  username: risk_first
  card: summary
  title: Risk-First Software Development 


defaults:
  - scope:
      path: ""
    values:
      image: /images/R1_logo_black.png

page_lang: en-GB  
description: Risk-First is a wiki about applying risk theory and practice to Software Development.  It presents a pattern language of risks that are applicable in software development. 
logo: /images/R1_logo_black.png
author: risk_first
title: Risk-First


webmaster_verifications:
  google: _Ah_sAWlHVd7-glADdzxCZLqt-HDlhCXLlMqlQGqLE4
  bing: 9DFE22A35BB1805E3474C158DC853AB4
  
permalink: /:categories/:year/:month/:day/:title