theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
twitter:
  username: risk_first
  card: summary
  
description: Risk-First is a collection of articles about applying Risk Management theory and practice to Software Development.
logo: images/R1_logo_black.png
author: risk_first

seo_tag:
  site_title: Risk-First

webmaster_verifications:
  google: _Ah_sAWlHVd7-glADdzxCZLqt-HDlhCXLlMqlQGqLE4
  bing: 9DFE22A35BB1805E3474C158DC853AB4