theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
twitter:
  username: risk_first
  
description: Risk-First is a collection of articles about applying Risk Management theory and practice to Software Development.
logo: https://riskfirst.org/images/R1_logo_black.png
author: risk_first
title: Risk-First Software Development 


webmaster_verifications:
  google: _Ah_sAWlHVd7-glADdzxCZLqt-HDlhCXLlMqlQGqLE4
  bing: 9DFE22A35BB1805E3474C158DC853AB4