# Site
name: "Risk-First"
title: "Risk-First Software Development"
description: "Risk-First is a wiki about applying risk theory and practice to Software Development.  It presents a pattern language of risks that are applicable in software development." 
logo: 'images/R1_logo_grue.png'
favicon: favicon.ico
author: risk_first
page_lang: en-GB  
permalink: /:categories/:year/:month/:day/:title

# Authors
authors:
  rob:
    name: Rob
    display_name: Rob Moffat
    gravatar: 29de34339da3e024b8e6974b05c74530
    email: rob@kite9.com
    web: https://robmoff.at
    description: "Author of Risk-First Software Development and full-stack developer working in the UK.  "


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/    

# Twitter  
twitter:
  username: risk_first
  card: summary_large_image
  title: Risk-First Software Development 

# Post Defaults
defaults:
  - scope:
      path: ""
    values:
      author: rob
      layout: post
      date: 24-02-2019
      categories: 
        - Post

# Analytics
webmaster_verifications:
  google: _Ah_sAWlHVd7-glADdzxCZLqt-HDlhCXLlMqlQGqLE4
  bing: 9DFE22A35BB1805E3474C158DC853AB4
  
