theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  
twitter:
  username: risk_first
  card: summary
  
description: Risk-First is a collection of articles about applying risk management practices to Software Development.
logo: images/R1_logo_black.png
author: Rob Moffat